### PR TITLE
Quotation Print format fixes

### PR DESCRIPTION
**Pull request by vimalraj27**
Minor changes in Print format
Screenshot:
Screenshot from 2022-07-28 10-13-51

### CODE REVIEW

**Comment by Ponnusamy1-V** [comment]
What are that minor changes

**Comment by Ponnusamy1-V** [comment]
Two colons are there near **To** on top left

**Review by vignesh235 — APPROVED** [review]

**Comment by vimalraj27** [comment]
> What are that minor changes

Updated the changes done in the description.

**Comment by vimalraj27** [comment]
> Two colons are there near **To** on top left

It was fixed, just attached the wrong screenshot.

**Pull request merged**
